
console.log("VITE_SUPABASE_URL:", process.env.VITE_SUPABASE_URL ? "PRESENT" : "MISSING");
console.log("VITE_SUPABASE_SERVICE_ROLE_KEY:", process.env.VITE_SUPABASE_SERVICE_ROLE_KEY ? "PRESENT" : "MISSING");
